### ISSUE TITLE
Pirk (ting som skal ses på til slutt)

### ISSUE THREAD

**Issue by icanseetime** [icanseetime/ntnu-idg3800-avgangsutstilling2022#27]
## Generelt

- [x] Fjerne alle console.log()'s
- [x] Se over alt som er kommentert ut og fjerne alle unødvendige kommentarer/kode
- [x] Gå gjennom alle ESLint warnings
- [x] Finne ut hvorfor det kommer et "loading-indicator" symbol helt nederst på siden iblant (gatsby-qod)

## Generell styling

- [x] Legge inn fonter på brødtekst (`<p>`) i global styles
- [x] Fikse side-scroll på enkelte sider (hvis det fortsatt er et problem)
- [x] Se over breakpoints/media queries 
- [x] Sjekk at alle fonter stemmer
- [x] Fikse min-height på main så footeren synes hvis det er lite innhold

## BioCard

- [x] Bio-tekst skal være over SocialLinks
- [x] Litt mindre mellomrom mellom bilde og biotekst

## SocialLinks

- [x] Velge hvilken av de to løsningene som skal brukes for SocialLinks
- [x] Litt bredere / avlange ikon-knapper på SocialIcons

## Footer

- [x] Sette litt fast margin over footeren?

## BackLink

- [x] Fikse slik at ikke begge ikonene genereres i DOM
- [x] Fixed position uten at den går over menyen
- [x] Fikse bredden på den, slik at man ikke trykker på knappen på høyresiden av skjermen

**Comment by IchorAmoc** [comment]
- [ ] Test at header ikke forsvinner når man scroller i mobil
